# Generated by Django 6.0.4 on 2026-04-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilTangkap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kondisi', models.CharField(choices=[('segar', 'Segar'), ('beku', 'Beku'), ('olahan', 'Olahan')], default='segar', max_length=10)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jenis_ikan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hasil_tangkap', to='master.jenisikan')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tangkap', to='operasional.trip')),
            ],
            options={
                'verbose_name_plural': 'Hasil Tangkap',
            },
        ),
    ]
