# Generated by Django 6.0.4 on 2026-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangkap', '0002_hasiltangkap_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasiltangkap',
            name='foto_bukti',
            field=models.ImageField(blank=True, null=True, upload_to='tangkap/bukti/'),
        ),
    ]
