# Generated by Django 6.0.4 on 2026-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangkap', '0004_hasiltangkap_dibuat_pada'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasiltangkap',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hasiltangkap',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
