# Generated by Django 6.0.4 on 2026-04-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('operasional', '0001_initial'),
        ('tangkap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_terjual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tgl_jual', models.DateField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('hasil_tangkap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penjualan', to='tangkap.hasiltangkap')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penjualan', to='master.pembeli')),
            ],
            options={
                'verbose_name_plural': 'Data Penjualan',
                'ordering': ['-tgl_jual'],
            },
        ),
        migrations.CreateModel(
            name='BagiHasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sudah_dibayar', models.BooleanField(default=False)),
                ('tgl_bayar', models.DateField(blank=True, null=True)),
                ('abk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bagi_hasil', to='master.abk')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagi_hasil', to='operasional.trip')),
            ],
            options={
                'verbose_name_plural': 'Bagi Hasil ABK',
                'unique_together': {('trip', 'abk')},
            },
        ),
    ]
