# Generated by Django 6.0.4 on 2026-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_penjualan_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='foto_bukti',
            field=models.ImageField(blank=True, null=True, upload_to='penjualan/bukti/'),
        ),
    ]
