# Generated by Django 6.0.4 on 2026-05-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0003_penjualan_foto_bukti'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
