# Generated by Django 6.0.4 on 2026-04-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_berangkat', models.DateField()),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('persiapan', 'Persiapan'), ('berlayar', 'Sedang Berlayar'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='persiapan', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('kapal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='master.kapal')),
            ],
            options={
                'verbose_name_plural': 'Data Trip',
                'ordering': ['-tgl_berangkat'],
            },
        ),
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('bbm', 'BBM'), ('es', 'Es Balok'), ('logistik', 'Logistik / Perbekalan'), ('perawatan', 'Perawatan Alat'), ('lainnya', 'Lainnya')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biaya_operasional', to='operasional.trip')),
            ],
            options={
                'verbose_name_plural': 'Biaya Operasional',
            },
        ),
        migrations.CreateModel(
            name='TripABK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_abk', to='master.abk')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_abk', to='operasional.trip')),
            ],
            options={
                'verbose_name': 'ABK Trip',
                'unique_together': {('trip', 'abk')},
            },
        ),
    ]
