# Generated by Django 6.0.4 on 2026-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayaoperasional',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
