# Generated by Django 6.0.4 on 2026-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0002_biayaoperasional_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_laporan_locked',
            field=models.BooleanField(default=False),
        ),
    ]
