# Generated by Django 6.0.4 on 2026-05-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0003_trip_is_laporan_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayaoperasional',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
