# Generated by Django 6.0.4 on 2026-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0005_biayaoperasional_foto_bukti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-dibuat_pada', '-id'], 'verbose_name_plural': 'Data Trip'},
        ),
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
