# Generated by Django 6.0.4 on 2026-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('persentase_bagi_hasil', models.DecimalField(decimal_places=2, help_text='Persentase dari laba bersih, contoh: 10.00', max_digits=5)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ABK',
                'verbose_name_plural': 'Data ABK',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisIkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('satuan', models.CharField(default='kg', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis Ikan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kapal', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=50)),
                ('kapasitas', models.DecimalField(decimal_places=2, help_text='Kapasitas dalam ton', max_digits=8)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('perbaikan', 'Dalam Perbaikan')], default='aktif', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kapal',
                'ordering': ['nama_kapal'],
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pembeli',
                'ordering': ['nama'],
            },
        ),
    ]
