# Generated by Django 6.0.4 on 2026-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abk',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='abk',
            name='persentase_bagi_hasil',
        ),
    ]
