# Generated by Django 6.0.4 on 2026-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_abk_nik_remove_abk_persentase_bagi_hasil'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisikan',
            name='harga_minimum',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Harga minimum per kg (Rp). Kosongkan jika tidak ada batasan.', max_digits=12, null=True),
        ),
    ]
