# Generated by Django 6.0.4 on 2026-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_jenisikan_harga_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kapal/'),
        ),
    ]
