# Generated by Django 6.0.4 on 2026-05-30 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_kapal_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorKapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='master.kapal')),
                ('operator', models.ForeignKey(limit_choices_to={'profile__role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='kapal_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penugasan Operator',
                'verbose_name_plural': 'Penugasan Operator',
                'unique_together': {('operator', 'kapal')},
            },
        ),
    ]
